{{- if .Values.serviceAccount.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vsphere-csi-controller
  namespace: kube-system
  labels:
    {{- include "vsphere-csi.labels" . | nindent 4 }}
{{- end -}}
