{{- if .Values.serviceAccount.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ .Values.serviceAccount.name }}"
  namespace: "{{ .Values.serviceAccount.namespace }}"
  labels:
    {{- include "vsphere-csi.labels" . | nindent 4 }}
{{- end -}}
